version: '3.9'

services:

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - ./dev/urandom:/dev/random:ro
    ports:
      - "8200:3000"
    restart: unless-stopped 
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: User
      MB_DB_PASS: p4ssw0rd
      MB_DB_HOST: postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped 
    environment:
      POSTGRES_USER: User
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: p4ssw0rd

