version: '3.3'

services:

  metabase-secrets:
    image: metabase/metabase:latest
    container_name: metabase-secrets
    hostname: metabase-secrets
    volumes: 
    - ./dev/urandom:/dev/random:ro
    ports:
      - "8200:3000"
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: User
      MB_DB_PASS: p4ssw0rd
      MB_DB_HOST: postgres-secrets
    depends_on: 
      - postgres-secrets


  postgres-secrets:
    image: postgres:latest
    container_name: postgres-secrets
    hostname: postgres-secrets
    environment:
      POSTGRES_USER: User
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: p4ssw0rd
